on:
  schedule:
    - cron: 0 1 * * *
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://renovate/renovate:19.66
        env:
          RENOVATE_PLATFORM: github
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING: true
