name: Deps

on:
  schedule:
    - cron: 0 1 * * *

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
    - run: docker run -e RENOVATE_PLATFORM -e RENOVATE_TOKEN renovate/renovate:${IMAGE_TAG} ${RENOVATE_REPOSITORIES}
      env:
        IMAGE_TAG: 19.70
        RENOVATE_PLATFORM: github
        RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
        RENOVATE_REPOSITORIES: ${{ github.repository }}
